# A: Dataset
dataset_dir: HO3D_v3/train
max_continuous_mapping: 8
# usual setting
#train_sequences: ["ABF10", "BB10", "GPMF10", "GSF10", "MDF10", "SB10", "ShSu10"]
#val_sequences: ["SiBF10", "SMu40"]

# self-test setting
#train_sequences: ["ABF10", "BB10", "GPMF10", "GSF10", "MDF10", "SB10", "ShSu10"]
#val_sequences: ["ABF10", "BB10", "GPMF10", "GSF10", "MDF10", "SB10", "ShSu10"]

# quick self-test setting
train_sequences: ["ABF10"]
val_sequences: ["ABF10"]

# B: Training
lr: 1e-4
epoch_num: 1000
batch_size: 128
max_kl_beta: 0.01
output_model_path: mvae_model_${epoch_num}epoch_quick_selftest.pth
normalize: True
beta_increment: True
input_pred: True

# C: eval
eval_every_epoch: 100

# D: Visualizing
model_path: ${output_model_path}

# Others
wandb_entity: howbullet
wandb_project: mvae_train
