wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1680159046.026947
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.13.10
      8:
      - 5
architecture:
  desc: null
  value: mlp
epoch:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.01
